*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOT_29_MV.......................................*
FORM GET_DATA_ZOT_29_MV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOT_29_T_MV_IT WHERE
(VIM_WHERETAB) .
    CLEAR ZOT_29_MV .
ZOT_29_MV-MANDT =
ZOT_29_T_MV_IT-MANDT .
ZOT_29_MV-PERSONEL_NO =
ZOT_29_T_MV_IT-PERSONEL_NO .
ZOT_29_MV-TELEFON =
ZOT_29_T_MV_IT-TELEFON .
ZOT_29_MV-IL =
ZOT_29_T_MV_IT-IL .
    SELECT SINGLE * FROM ZOT_29_T_MV_AT WHERE
PERSONEL_NO = ZOT_29_T_MV_IT-PERSONEL_NO .
    IF SY-SUBRC EQ 0.
ZOT_29_MV-AD =
ZOT_29_T_MV_AT-AD .
ZOT_29_MV-SOYAD =
ZOT_29_T_MV_AT-SOYAD .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOT_29_MV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOT_29_MV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOT_29_MV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOT_29_MV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOT_29_T_MV_IT WHERE
  PERSONEL_NO = ZOT_29_MV-PERSONEL_NO .
    IF SY-SUBRC = 0.
    DELETE ZOT_29_T_MV_IT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOT_29_T_MV_IT WHERE
  PERSONEL_NO = ZOT_29_MV-PERSONEL_NO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOT_29_T_MV_IT.
    ENDIF.
ZOT_29_T_MV_IT-MANDT =
ZOT_29_MV-MANDT .
ZOT_29_T_MV_IT-PERSONEL_NO =
ZOT_29_MV-PERSONEL_NO .
ZOT_29_T_MV_IT-TELEFON =
ZOT_29_MV-TELEFON .
ZOT_29_T_MV_IT-IL =
ZOT_29_MV-IL .
    IF SY-SUBRC = 0.
    UPDATE ZOT_29_T_MV_IT ##WARN_OK.
    ELSE.
    INSERT ZOT_29_T_MV_IT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOT_29_MV-UPD_FLAG,
STATUS_ZOT_29_MV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZOT_29_MV.
  SELECT SINGLE * FROM ZOT_29_T_MV_IT WHERE
PERSONEL_NO = ZOT_29_MV-PERSONEL_NO .
ZOT_29_MV-MANDT =
ZOT_29_T_MV_IT-MANDT .
ZOT_29_MV-PERSONEL_NO =
ZOT_29_T_MV_IT-PERSONEL_NO .
ZOT_29_MV-TELEFON =
ZOT_29_T_MV_IT-TELEFON .
ZOT_29_MV-IL =
ZOT_29_T_MV_IT-IL .
    SELECT SINGLE * FROM ZOT_29_T_MV_AT WHERE
PERSONEL_NO = ZOT_29_T_MV_IT-PERSONEL_NO .
    IF SY-SUBRC EQ 0.
ZOT_29_MV-AD =
ZOT_29_T_MV_AT-AD .
ZOT_29_MV-SOYAD =
ZOT_29_T_MV_AT-SOYAD .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOT_29_MV-AD .
      CLEAR ZOT_29_MV-SOYAD .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOT_29_MV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOT_29_MV-PERSONEL_NO TO
ZOT_29_T_MV_IT-PERSONEL_NO .
MOVE ZOT_29_MV-MANDT TO
ZOT_29_T_MV_IT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOT_29_T_MV_IT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOT_29_T_MV_IT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOT_29_T_MV_IT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOT_29_MV USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOT_29_T_MV_IT-MANDT =
ZOT_29_MV-MANDT .
ZOT_29_T_MV_IT-PERSONEL_NO =
ZOT_29_MV-PERSONEL_NO .
ZOT_29_T_MV_IT-TELEFON =
ZOT_29_MV-TELEFON .
ZOT_29_T_MV_IT-IL =
ZOT_29_MV-IL .
    SELECT SINGLE * FROM ZOT_29_T_MV_AT WHERE
PERSONEL_NO = ZOT_29_T_MV_IT-PERSONEL_NO .
    IF SY-SUBRC EQ 0.
ZOT_29_MV-AD =
ZOT_29_T_MV_AT-AD .
ZOT_29_MV-SOYAD =
ZOT_29_T_MV_AT-SOYAD .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOT_29_MV-AD .
      CLEAR ZOT_29_MV-SOYAD .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
